### ISSUE TITLE
Use object-assign to merge passed in style objects with built-ins

### ISSUE THREAD

**Issue by KyleAMathews** [chantastic/react-media-object#8]

**Comment by chantastic** [comment]
Thanks @KyleAMathews for the issue!

I wasn't entirely sure how I had wanted to resolve this before, but I've been playing with a few options here at work and am starting to boil it down.

My concern with merging styles is that it becomes much more difficult to clear out styles you don't want...

To solve this, I've been been taking `noStyle` as a prop to short-curcuit the assignment of default styles.

What are your thoughts on that? Is there a better name I could use?

**Comment by chantastic** [comment]
Let me know if PR #10 is along the lines of what you were hoping for.
