### ISSUE TITLE
Option to right align image

### ISSUE THREAD

**Issue by KyleAMathews** [chantastic/react-media-object#9]

**Comment by chantastic** [comment]
What would your ideal API for this be?

I think I'd want to have symmetry with the left-image API and have `Media` be smart enough to know how to apply styles (based on the order of `children`):

``` js
<Media>
  <Bd>...</Bd>
  <Img>...</Img>
</Media>
```

I'd like to keep it somewhat unopinionated about what children are passed in. Do you think a simple check for to see if it's the first-or-last element would suffice?

**Comment by KyleAMathews** [comment]
That sounds great! Would be pretty intuitive I think.

**Comment by chantastic** [comment]
Realizing that my first thought was pretty niave. Floats obviously don't work that way (doh!).

The `<Img />` will need to come first regardless. What would you say to prop `position` which accepts `left` or `right` and defaults to `left`?

**Comment by KyleAMathews** [comment]
How about `reversed`? Both these two articles use that word:
- https://philipwalton.github.io/solved-by-flexbox/demos/media-object/
- http://codepen.io/siiron/pen/kHdlp

**Comment by KyleAMathews** [comment]
Also the "flag object" pattern (in the second article above) is cool as we could add vertical-alignment as an option.

**Comment by chantastic** [comment]
That's way better. Thanks!

**Comment by chantastic** [comment]
@KyleAMathews this is in `master` now:

```
<Media reverse>
  ...
</Media>
```

Thanks for the help on this.
